### ISSUE TITLE
Server Initiation

### ISSUE THREAD

**Issue by ghost** [NN-Dev-Team/Nordic-Network#11]
To start a server, you have given these instructions:
1. Go to your terminal, execute `cd path/to/github/projects/Nordic-Network/private` and after that execute `node controlpanel-server`. Make sure node.js **AND required libraries are installed**.
2. **Start your browser** and go to "localhost:15015", press Inspect Element and click on "Console". Then type in "startServer(0, "01234569abcdef");" and press enter. The server will now start on your computer.

I have some concerns with some parts of the instructions, I have bolded relevant areas.
1. Why does the user need to install the separate libraries? I believe that this whole program should be self-contained, all libraries should be installed/bundled within the repository.
2. Why does the server need to be started from within a browser? Surely `controlpanel-server.js` should start the server?

Because I'm not entirely sure of what's what, I explain part 2 here:

If `controlpanel-server.js` is intended to be a web server, serving a web page that a remote user interacts with, then it should use port 80, not 15015. Further, if a remote user is meant to interact with a website to start a server on their own computer, they will not be able to unless they download some external programs, but then the website becomes extraneous. I'm just confused as to what `controlpanel-server.js` is meant to do.

**Comment by TropicSapling** [comment]
These instructions are for _testing only_. Of course users using the service won't need to do this, this is just for developers so that we can test if the code is working. All these files will be on the server, not on the users' computers :)

**Comment by ghost** [comment]
What's the point of the browser interface then? Surely a command-line API would make more sense.

**Comment by TropicSapling** [comment]
? Everything in the public folder will be sent to the people viewing the webpage, and when they for example click a start button socket.io will send a msg to the server that controlpanel-server.js receives and starts the server using the information sent.

Currently most stuff is console based, but as soon as the design is done you won't need to use the console anymore and you'll instead just click buttons and stuff on the website :)

**Comment by ghost** [comment]
So the user of the website doesn't run the server on their computer?

**Comment by TropicSapling** [comment]
No...

**Comment by ghost** [comment]
Then I'd recommend removing the "The server will now start on your computer." bit from the instructions. It is very ambiguous.

**Comment by TropicSapling** [comment]
Well I meant you _can_ run the server on your computer using these instructions, but it's just for testing and it will only be open locally unless you've done port-forwarding. I guess I can make the instructions a bit more clear :)

**Comment by ghost** [comment]
Okay, I get it now, thank you :+1:

**Comment by TropicSapling** [comment]
@theonlygusti check new issue #12
