### ISSUE TITLE
Created server counter on index page is unreadable on mobile

### ISSUE THREAD

**Issue by saskakol** [NN-Dev-Team/Nordic-Network#125]
Fine on desktop, since the dark text is against a light background. On mobile, though, the background image is shifted down, and now there is dark text on a dark background. This makes the text tough to read.

Suggested fixes:

- Replace background image with something else
- Change text color on mobile with breakpoints
- Vertically center image using CSS

**Comment by TropicSapling** [comment]
Yeah I noticed this myself too after a while, didn't prioritise fixing it though due to it being relatively unimportant. How to change the text colour with breakpoints though?

**Comment by TropicSapling** [comment]
@iSasFTW Fixed in https://github.com/NN-Dev-Team/Nordic-Network/commit/ca886966be769e9bb1cb33eafaeaf3cc5c9d9e05? Or atleast it's about as readable on mobile as on the computer now

**Comment by TropicSapling** [comment]
Closing this as it seems to have been fixed, or atleast partially :)
