### ISSUE TITLE
Our slack integration may not be working....

### ISSUE THREAD

**Issue by ghost** [NN-Dev-Team/Nordic-Network#5]
Just a test to see what Jack's slack integration will detect. This issue can be instantly closed.

**Comment by TropicSapling** [comment]
Hmm doesn't seem to be working for me? Atleast not on the app :/

**Comment by TropicSapling** [comment]
Bump

**Comment by TropicSapling** [comment]
Test

**Comment by TropicSapling** [comment]
Test 2

**Comment by TropicSapling** [comment]
It's confirmed that it's working now :)
Closing issue.

**Comment by jackmawer** [comment]
I can confirm that I've fixed the bot. Next time please mention me!

**Comment by TropicSapling** [comment]
Testing
