### ISSUE TITLE
sendFile() not working second time used

### ISSUE THREAD

**Issue by TropicSapling** [NN-Dev-Team/Nordic-Network#6]
For some reason calling `res.sendFile()` twice causes it to not go up one directory when it should:

```
app.get('/', function(req, response){
    response.set('content-type', 'text/plain');
    response.sendFile(path.join(__dirname, '../public/php/controlpanel.php'));
    response.sendFile(path.join(__dirname, '../public/js/controlpanel-client.js'));
});
```

Error showed after executing says that directory `/private/public/controlpanel-client.js` doesn't exist which indeed is correct, but it's looking in the wrong folder. It's supposed to go up one folder and look in `public/js/controlpanel-client.js`, but for some reason it doesn't :/
And the weirdest thing is that the first `sendFile()` works, the php file does get sent, but the js file doesn't...

**If this doesn't get fixed soon I can't test if the control panel is working correctly, and therefore it's going to be harder to continue developing. This also must be fixed for the control panel to work in the end.**

**Comment by ghost** [comment]
So what are you trying to fix? Are you trying to send two files? I don't think that's possible.

**Comment by TropicSapling** [comment]
@jay4 is it possible if done in 2 seperate files?

**Comment by ghost** [comment]
It's hard to know without knowing exactly what you're trying to do here. Why are you serving PHP files? Isn't this a socket.io server?

**Comment by TropicSapling** [comment]
@jay4 Pretty sure it's just html with a little bit of PHP in it, @ethernity4ever wrote that he was going to use the .php extension for his website files so I changed .html to .php :)

(That means the php file is going to act pretty much like a normal html web page. Also sorry for the late reply I'm sick)

**Comment by ghost** [comment]
btw - if you think people will be confused that `res` will mean "resolution", you can always just change `res` to `response` to make it clearer :)

**Comment by TropicSapling** [comment]
@jay4 Oh yeah you're right :package:
Still back to the issue:
**For some reason calling `res.sendFile()` twice causes it to not go up one directory when it should**.

And if you can't call it twice then back to this:

> is it possible if done in 2 seperate files?

**Comment by ghost** [comment]
Of course! Try it

**Comment by TropicSapling** [comment]
@jay4 I'll try it then as soon as I'm a bit better :)

**Comment by TropicSapling** [comment]
Nvm this found a way which I only need to send 1 file :)
